# Generated by Django 2.2.1 on 2019-05-30 03:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('residencies', '0002_auto_20190530_0314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resident',
            name='checked_out_by',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='checked_out_by', to='staffs.Staff'),
        ),
    ]
