# Generated by Django 2.2.1 on 2019-05-30 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('residencies', '0006_auto_20190530_0321'),
    ]

    operations = [
        migrations.AddField(
            model_name='resident',
            name='checked_out_time',
            field=models.DateField(blank=True, null=True),
        ),
    ]
