# Generated by Django 2.2.1 on 2019-05-30 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('residencies', '0007_resident_checked_out_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resident',
            name='checked_out_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
