# Generated by Django 2.2.1 on 2019-05-30 15:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('staffs', '0001_initial'),
        ('residencies', '0008_auto_20190530_1515'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='inspected_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inspected_by', to='staffs.Staff'),
        ),
        migrations.AddField(
            model_name='room',
            name='inspection_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='pass_inspection',
            field=models.BooleanField(default=False),
        ),
    ]
