# Generated by Django 2.2.1 on 2019-05-30 03:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('residencies', '0001_initial'),
        ('IRs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ir',
            name='building',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='residencies.Building'),
        ),
    ]
